if is_plat("windows") then
	includes(
		--'TestApp1',
		'Client',
		'Server',
		'DuiLibApp',
		'LuaDuiLibApp',
		'ListDemo',
		--'QQDemo',
		--'RichListDemo',
		--'ScrCapture',
		--'360SafeDemo',
		--'GameDemo',
		'MyControls',
		'YMusic',
		'ConvexBrowser'
	)
else
end